starkware-libs/committer

crates/committer/src/patricia_merkle_tree/filled_node.rs

The hash version is required because I think that we want python to be the source of truth.
It's being used [here](https://github.com/starkware-industries/starkware/blob/dev/src/starkware/starknet/business_logic/fact_state/contract_class_objects.py#L110) and [here](https://github.com/starkware-industries/starkware/blob/dev/src/starkware/starknet/business_logic/fact_state/contract_state_objects.py#L87).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/11)

fix: added some more types to committer

---

crates/committer/src/patricia_merkle_tree/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/21)

fix: change path length to u8

---

crates/committer/src/lib.rs
crates/committer/src/patricia_merkle_tree/current_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/errors.rs
crates/committer/src/patricia_merkle_tree/filled_tree.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs
crates/committer/src/storage.rs
crates/committer/src/storage/errors.rs
crates/committer/src/storage/storage_trait.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/26)

build: add storage trait and FilledTree::serialize

---

crates/committer/src/hash.rs
crates/committer/src/hash/hash_trait.rs
crates/committer/src/hash/pedersen.rs
crates/committer/src/patricia_merkle_tree/filled_node.rs
crates/committer/src/patricia_merkle_tree/filled_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_node.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/types_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_node.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/42)

chore: rename types to hash_trait and add pedersen file

---

crates/committer/src/patricia_merkle_tree/filled_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/44)

fix: changes to api

---

Cargo.lock
Cargo.toml
crates/committer/Cargo.toml
crates/committer/src/patricia_merkle_tree.rs
crates/committer/src/patricia_merkle_tree/errors.rs
crates/committer/src/patricia_merkle_tree/filled_node.rs
crates/committer/src/patricia_merkle_tree/filled_tree.rs
crates/committer/src/patricia_merkle_tree/serialized_node.rs
crates/committer/src/types.rs

This pull request introduces a serialization method for filled nodes in the Patricia Merkle tree implementation. The serialise method is implemented for the FilledNode type, allowing the conversion of filled nodes into byte vectors.
The method serializes the filled node into a byte vector according to the following rules:
For binary nodes: Concatenates the left and right hashes.
For edge nodes: Concatenates the bottom hash, path, and path length.
For leaf nodes: Concatenates the node's hash.
This functionality enhances the usability of the filled node struct by providing a convenient way to serialize its data for storage or transmission.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

feat: add serialize method to filled_node

---

crates/committer/src/storage.rs
crates/committer/src/storage/serde_trait.rs

Fix the wrong error type in serde trait,  and declare serde trait as a module.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/48)

fix: wrong return type in serde trait

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/original_skeleton_calc_test.rs

When fetching sibling leaves from storage, we shouldn't read the preimage of the leaf hash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/58)

fix: fetch_nodes method shouldn't read leaves from storage

---

crates/committer/src/patricia_merkle_tree/filled_tree/node.rs
crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs
crates/committer/src/patricia_merkle_tree/node_data.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/63)

chore: add node_data/leaf_serde

---

crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/53)

test: test_tree_with_sibling_nodes

---

Cargo.lock
Cargo.toml
crates/committer/Cargo.toml
crates/committer/src/storage.rs
crates/committer/src/storage/map_storage.rs
crates/committer/src/storage/storage_trait.rs
crates/committer_cli/src/tests/python_tests.rs

Introduces storage_serialize_test function to generate and serialize a MapStorage instance containing StorageKey and StorageValue pairs for values in the range 0..=99. Enabling serialization of MapStorage to JSON format using Serde.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/82)

build: impl serialization for storage

---

crates/committer/src/patricia_merkle_tree/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/103)

fix: removed implicit conversion felt => NodeIndex

---

Cargo.lock
Cargo.toml
crates/committer/Cargo.toml
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/types_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/98)

chore: get_lca for NodeIndex

---

crates/committer/src/patricia_merkle_tree.rs
crates/committer/src/patricia_merkle_tree/test_utils.rs
crates/committer/src/patricia_merkle_tree/types_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/111)

test(skeleton): get_random_u256

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs
crates/committer/src/patricia_merkle_tree/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/112)

chore(skeleton): common split_leaves function

---

crates/committer/src/hash.rs
crates/committer/src/hash/poseidon.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/121)

fix: fix bug in tree hash function definition

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs
crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf.rs
crates/committer/src/patricia_merkle_tree/test_utils.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/node.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/129)

feat(skeleton): add_construct_from_dege_data

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/node.rs
crates/committer/src/patricia_merkle_tree/test_utils.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/node.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/137)

feat(skeleton): add_node_from_binary_data

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/node.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/145)

chore(skeleton): replace EdgeSibling with UnmodifiedBottom in original

---

crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs
crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs
crates/committer/src/patricia_merkle_tree/node_data/errors.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/160)

feat: move leaf fetching logic to leaf data trait

---

Cargo.lock
Cargo.toml
commitlint.config.js
crates/committer_cli/Cargo.toml
crates/committer_cli/src/block_hash.rs
crates/committer_cli/src/main.rs
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/173)

feat(block_hash): add basic block info command

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/180)

refactor: remove the tree_height field inside original skleton tree

---

crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs
crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs
crates/committer/src/patricia_merkle_tree/node_data/errors.rs
crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/test_utils.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/types_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs
crates/committer/src/storage/errors.rs
crates/committer_cli/src/tests/python_tests.rs
crates/committer_cli/src/tests/utils/random_structs.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/177)

chore(skeleton): hide private field in EdgePathLength

---

.github/workflows/ci.yml
Cargo.toml
crates/committer_cli/Cargo.toml
scripts/taplo.sh
taplo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/181)

feat: toml formatting verification in CI

---

crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/186)

fix: wrong handling of insert return value

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/191)

refactor: remove tree height field from updated skeleton tree

---

crates/committer/src/felt.rs
crates/committer/src/patricia_merkle_tree/types_test.rs
crates/committer_cli/src/parse_input/read_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/198)

build: impl debug for felt

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/types_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/203)

chore: support u128 addition with NodeIndex

---

crates/committer/Cargo.toml
crates/committer/src/patricia_merkle_tree.rs
crates/committer/src/patricia_merkle_tree/external_test_utils.rs
crates/committer/src/patricia_merkle_tree/internal_test_utils.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs
crates/committer/src/patricia_merkle_tree/types_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs
crates/committer_cli/src/tests/utils/random_structs.rs

Separate between test and testing. Now, the test depends on testing, meaning that cfg(test) also compiles the testing file, 
but testing does not include a test file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/211)

refactor: change the hierarchy between test and testing

---

crates/committer_cli/src/tests/python_tests.rs
crates/committer_cli/src/tests/utils/objects.rs

Replace block info test with tx data test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/216)

test(block_hash): tx data test

---

crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/221)

refactor(skeleton): rename updated skeleton compute file to create_tree_helper

---

crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/230)

fix: tree hash function for compiled class hash tree

---

crates/committer/src/block_committer/commit.rs
crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/skeleton_forest.rs
crates/committer_cli/src/filled_tree_output/filled_forest.rs
crates/committer_cli/src/tests/python_tests.rs
crates/committer_cli/src/tests/utils/random_structs.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/285)

refactor: removed forest traits

---

crates/committer_cli/src/tests/benchmark_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/293)

refactor: desrialization structs for regression test output

---

.github/workflows/ci.yml
crates/committer_cli/src/tests.rs
crates/committer_cli/src/tests/regression_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/295)

refactor: rename benchmark_tests to regression_tests

---

crates/committer_cli/benches/committer_bench.rs
crates/committer_cli/src/commands.rs
crates/committer_cli/src/main.rs
crates/committer_cli/src/tests/regression_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/297)

refactor: commit function

---

crates/committer/src/block_committer/commit.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/307)

refactor: no need to recalculate the actual updates

---

crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs
crates/committer/src/patricia_merkle_tree/internal_test_utils.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/storage/db_object.rs
crates/committer/src/storage/errors.rs
crates/committer/src/storage/storage_trait.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/314)

build: impl mock test utils

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/316)

refactor: use mock leaf in create tree test

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs
crates/committer/src/patricia_merkle_tree/internal_test_utils.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/319)

refactor: use mock test utils in filled tree test
