starkware-libs/committer

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/2)

chore: remove tmp_venv from gitignore (blockifier artifact)

---

Cargo.lock
crates/committer/Cargo.toml
crates/committer/src/hash.rs
crates/committer/src/hash/types.rs
crates/committer/src/lib.rs
crates/committer/src/patricia_merkle_tree.rs
crates/committer/src/patricia_merkle_tree/errors.rs
crates/committer/src/patricia_merkle_tree/filled_node.rs
crates/committer/src/patricia_merkle_tree/filled_tree.rs
crates/committer/src/patricia_merkle_tree/skeleton_node.rs
crates/committer/src/patricia_merkle_tree/skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/8)

build: add tentative tree API

---

crates/committer/src/patricia_merkle_tree/filled_node.rs
crates/committer/src/patricia_merkle_tree/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/10)

fix: fix TreeHashFunction and refactor FilledNode

---

crates/committer/src/patricia_merkle_tree/filled_tree.rs
crates/committer/src/patricia_merkle_tree/skeleton_tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/12)

fix: fix map and result order

---

crates/committer/src/patricia_merkle_tree/filled_node.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/13)

fix: implement LeafDataTrait for LeafData

---

crates/committer/src/hash/types.rs
crates/committer/src/patricia_merkle_tree/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/14)

fix: remove async

---

crates/committer/src/patricia_merkle_tree/filled_node.rs
crates/committer/src/patricia_merkle_tree/filled_tree.rs
crates/committer/src/patricia_merkle_tree/skeleton_node.rs
crates/committer/src/patricia_merkle_tree/skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/15)

chore: add documentation

---

crates/committer/src/patricia_merkle_tree/filled_tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/24)

fix: change FilledTree signature for interior mutability

---

crates/committer/src/hash/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/28)

build: add struct for pedersen hash impl

---

crates/committer/src/patricia_merkle_tree/test_utils.rs
crates/committer/src/patricia_merkle_tree/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/29)

build: add TreeHashFunctionTestingImpl for testing

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/45)

feat: push compiled binary to S3 on push to github

---

crates/committer/src/patricia_merkle_tree/errors.rs
crates/committer/src/patricia_merkle_tree/filled_node.rs
crates/committer/src/patricia_merkle_tree/filled_tree.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/43)

build: allow interior mutability

---

crates/committer/src/patricia_merkle_tree/filled_node.rs
crates/committer/src/patricia_merkle_tree/serialized_node.rs
crates/committer/src/storage/storage_trait.rs

Implementation of db_key function for filled node.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/49)

build: impl db key to filled node

---

.github/workflows/ci.yml
BUILD

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/52)

feat: pin ubuntu version in CI and export binaries locally

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/67)

fix: on push commit hash

---

crates/committer/src/felt.rs
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/76)

build: add felt serialization test

---

crates/committer/src/hash/hash_trait.rs
crates/committer/src/hash/pedersen.rs
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/77)

build: add hash test

---

crates/committer/src/felt.rs
crates/committer/src/patricia_merkle_tree/filled_tree/node.rs
crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf.rs
crates/committer/src/storage.rs
crates/committer/src/storage/errors.rs
crates/committer/src/storage/serde_trait.rs
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/78)

build: add binary serialization test

---

crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs
crates/committer_cli/src/tests/python_tests.rs

This PR introduces serialization tests and updates to ensure consistency between Python and Rust
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/75)

build: add serialization tests

---

crates/committer/src/block_committer.rs
crates/committer/src/block_committer/types.rs
crates/committer/src/lib.rs
crates/committer_cli/src/deserialization/cast.rs
crates/committer_cli/src/deserialization/read.rs
crates/committer_cli/src/deserialization/read_test.rs
crates/committer_cli/src/deserialization/types.rs
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/80)

build: move input definitions to committer crate

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs
crates/committer/src/storage/storage_trait.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/88)

chore: fix clippy 1.78 errors

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/87)

refactor: changed create_tree signature

---

commitlint.config.js
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/81)

chore(skeleton): function has_leaves_on_both_sides

---

crates/committer/src/block_committer/input.rs
crates/committer_cli/src/parse_input/cast.rs
crates/committer_cli/src/parse_input/raw_input.rs
crates/committer_cli/src/parse_input/read_test.rs
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/92)

refactor: renamed tree_height => tree_heights

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/compute_updated_skeleton_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/95)

refactor(skeleton): split OriginalSkeletonTree impls

---

crates/committer/src/block_committer/input.rs
crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs
crates/committer_cli/src/parse_input/cast.rs
crates/committer_cli/src/parse_input/read_test.rs
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/94)

fix: removed duplicate definitions of contract state leaf

---

crates/committer/src/block_committer/input.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/types_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/93)

build: creating upper tree as part of the original skeleton forest

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/114)

fix: modified indices should NOT be given as full indices

---

crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/119)

build: add is_empty method to UpdatedSkeletonTree

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/131)

refactor: skeleton leaf

---

crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs

…func
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/134)

feat(skeleton): move leaf finalization to UpdatedSkeletonTree create func

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/136)

chore: remove the generic type S from original skeleton forest

---

Cargo.lock
crates/committer/src/felt.rs
crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs
crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs
crates/committer/src/patricia_merkle_tree/test_utils.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/types_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs
crates/committer_cli/Cargo.toml
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/135)

refactor: change EdgePath internal type to U256

---

crates/committer/src/patricia_merkle_tree/errors.rs
crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs
crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/errors.rs
crates/committer/src/storage/map_storage.rs
crates/committer_cli/src/filled_tree_output.rs
crates/committer_cli/src/filled_tree_output/errors.rs
crates/committer_cli/src/filled_tree_output/filled_forest.rs
crates/committer_cli/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/132)

build: filled forest client

---

crates/committer/src/block_committer/commit.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/skeleton_forest.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/142)

refactor: move updated skeleton forest creation to be under updated skeleton forest

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs
crates/committer/src/patricia_merkle_tree/test_utils.rs
crates/committer/src/patricia_merkle_tree/types_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/151)

fix: add randomness fixture to tests

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/node.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/146)

chore(skeleton): replace edge_sibling with UnmodifiedBottom in updated

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/155)

fix: skeleton forest test

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/node.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/node.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/159)

chore(skeleton): skeleton Edge from struct to tuple struct

---

crates/committer_cli/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/174)

fix: delete hash versions as input, there is a regression test to verify it

---

crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs
crates/committer/src/patricia_merkle_tree/test_utils.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/192)

refactor: rename TreeHeight => SubTreeHeight and TreeHeight::MAX => TreeHeight::ACTUAL_HEIGHT

---

Cargo.lock
Cargo.toml
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/193)

feat(block_hash): add tx execution info

---

crates/committer/src/felt.rs
crates/committer/src/patricia_merkle_tree/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/197)

refactor: remove testing to test file

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/202)

fix: filter unmodified_bottom in initialize with placeholders

---

Cargo.lock
Cargo.toml
crates/committer_cli/Cargo.toml
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/201)

test(block_hash): parsing state diff

---

Cargo.lock
Cargo.toml
crates/committer_cli/src/tests/python_tests.rs
crates/committer_cli/src/tests/utils.rs
crates/committer_cli/src/tests/utils/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/214)

refactor(block_hash): move test objects

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/219)

fix: overflow bug

---

crates/committer_cli/src/block_hash.rs
crates/committer_cli/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/217)

feat(block_hash): add objects

---

crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/220)

test: remove as_fully_indexed second definition

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/compute_updated_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs

…dified bottom variants
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/213)

refactor: rename comments and functions after removing sibling & unmodified bottom variants

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/222)

refactor: rename test

---

crates/committer/src/block_committer/commit.rs
crates/committer/src/block_committer/errors.rs
crates/committer/src/block_committer/input.rs
crates/committer/src/forest_errors.rs
crates/committer/src/patricia_merkle_tree/external_test_utils.rs
crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs
crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs
crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs
crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function_test.rs
crates/committer_cli/src/filled_tree_output/errors.rs
crates/committer_cli/src/filled_tree_output/filled_forest.rs
crates/committer_cli/src/tests/python_tests.rs
crates/committer_cli/src/tests/utils/parse_from_python.rs
crates/committer_cli/src/tests/utils/random_structs.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/166)

chore!: refactor and split LeafDataImpl into structs

---

crates/committer_cli/src/main.rs
crates/committer_cli/src/parse_input/read.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/231)

feat(block_hash): read and write from file

---

crates/committer_cli/src/block_hash.rs
crates/committer_cli/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/226)

feat(block_hash): calculate block hash command

---

crates/committer/src/patricia_merkle_tree/node_data/leaf_serde.rs
crates/committer/src/storage/db_object.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/237)

build: add prefix to deserializable trait

---

crates/committer/src/block_committer/commit.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/238)

build: log out a warning for trivial nonce and class hash update

---

crates/committer/src/patricia_merkle_tree/external_test_utils.rs
crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs
crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs
crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs
crates/committer_cli/benches/committer_bench.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/232)

refactor: remove clones from benchmarking

---

.github/workflows/ci.yml
crates/committer_cli/benches/committer_bench.rs
crates/committer_cli/benches/committer_flow_inputs.json
crates/committer_cli/src/tests/benchmark_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/236)

test: add full committer flow benchmarking

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/234)

test: get bottom subtree

---

crates/committer/src/patricia_merkle_tree/external_test_utils.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/errors.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/241)

build: log out a warning when encountering a trivial update

---

crates/committer/src/block_committer/input.rs
crates/committer/src/patricia_merkle_tree/filled_tree/node.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf_serde_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/242)

build: adding get_leaves method to original skeleton tree

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/247)

refactor: deserializing leaves is not always necessary and could be expensive

---

crates/committer/src/block_committer/commit.rs
crates/committer/src/block_committer/input.rs
crates/committer/src/patricia_merkle_tree/filled_tree/forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/skeleton_forest.rs
crates/committer_cli/src/parse_input/cast.rs
crates/committer_cli/src/parse_input/raw_input.rs
crates/committer_cli/src/parse_input/read_test.rs
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/253)

refactor: remove usage of current contract state leaves

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/246)

chore: refactor ci.yml

---

crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs
crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/255)

fix: create of empty tree

---

crates/committer_cli/benches/committer_bench.rs
crates/committer_cli/src/commands.rs
crates/committer_cli/src/filled_tree_output/filled_forest.rs
crates/committer_cli/src/main.rs
crates/committer_cli/src/tests/benchmark_tests.rs
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/249)

feat: read and write from file in commit command

---

.github/workflows/ci.yml
crates/committer_cli/benches/committer_bench.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/251)

chore: add benchmarking to ci

---

crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/264)

test: panic before writing

---

crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/263)

fix: possible fix

---

crates/committer/src/patricia_merkle_tree/external_test_utils.rs
crates/committer/src/patricia_merkle_tree/filled_tree/tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/skeleton_forest.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/utils_test.rs
crates/committer/src/patricia_merkle_tree/types.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/create_tree_helper_test.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/261)

refactor: define a wrapper for sorted_leaf_indices

---

Cargo.lock
Cargo.toml
crates/committer_cli/Cargo.toml
crates/committer_cli/src/main.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/257)

build: add logger init

---

.github/workflows/ci.yml
crates/committer_cli/benches/bench_split_and_prepare_post.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/265)

fix: post only benchmarks that regressed or improved

---

crates/committer/src/block_committer/commit.rs
crates/committer/src/block_committer/input.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/272)

refactor: state diff

---

crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/273)

refactor: empty tree conditions

---

crates/committer/src/block_committer/input.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/274)

refactor: storage value derive copy

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/275)

fix: small typo

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/279)

ci: use versioning for bench and flow test input files - step 2

---

crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/280)

fix: trivial state diff log format consistency

---

crates/committer_cli/src/tests/benchmark_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/281)

test: add regression test for single tree flow

---

crates/committer_cli/src/tests/benchmark_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/291)

refactor: deserialize input in deserialize function

---

crates/committer_cli/src/tests/benchmark_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/294)

refactor: deserializer for expected facts

---

Cargo.lock
crates/committer_cli/Cargo.toml
crates/committer_cli/src/tests/python_tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/282)

test: log capture and panic message capture

---

crates/committer_cli/benches/committer_flow_inputs.json
crates/committer_cli/benches/tree_flow_inputs.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/305)

fix: typo in placeholder files

---

crates/committer/src/patricia_merkle_tree/external_test_utils.rs
crates/committer/src/patricia_merkle_tree/filled_tree/errors.rs
crates/committer/src/patricia_merkle_tree/filled_tree/node.rs
crates/committer/src/patricia_merkle_tree/filled_tree/node_serde.rs
crates/committer/src/patricia_merkle_tree/filled_tree/tree.rs
crates/committer/src/patricia_merkle_tree/node_data/inner_node.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf.rs
crates/committer/src/patricia_merkle_tree/node_data/leaf_serde_test.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/config.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/create_tree.rs
crates/committer/src/patricia_merkle_tree/original_skeleton_tree/tree.rs
crates/committer/src/patricia_merkle_tree/updated_skeleton_tree/hash_function.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/committer/306)

refactor: change leaf data name to leaf
